### PR TITLE
GitHubSync update - release-1.9

### PR DESCRIPTION
**Pull request by particularbot6**
This is an automated synchronization PR.

The following source template repositories were used:
* particular/RepoStandards

### CODE REVIEW

**Comment by DavidBoike** [comment]
Not stale, there's flaky/broken tests afoot.

**Comment by DavidBoike** [comment]
@dependabot rebase

**Comment by DavidBoike** [comment]
Ah, it's actualy GitVersion problems.

**Comment by kentdr** [comment]
This PR is way behind and needs to be re-created.

**Pull request closed without merging**
