### PR TITLE
Update test projects to NServiceBus 7.1

### PR DESCRIPTION
**Pull request by timbussmann**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Are we going to move forward with 7.1 or hold off for 7.2?

**Comment by SeanFeldman** [comment]
Typo, was supposed to be 7.1.1 🙂

**Comment by bording** [comment]
I think we can merge this as-is. We don't have to reference 7.1.1.

**Comment by SeanFeldman** [comment]
Since 7.1.1 is just analyzer change, 👍

**Pull request merged**
