### PR TITLE
Fix version number by ignoring a faulty commit

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Version fix seems to be correct as the version on the PR build is correct.

**Comment by timbussmann** [comment]
seems like this test is reliably failing

**Comment by SeanFeldman** [comment]
Strange, no tests were failing. I will rerun it again.

**Comment by SeanFeldman** [comment]
A random single test is failing and looks like it's related to the backend. Specifically, entity management.
Could be a temporary issue with the service.

**Pull request merged**
