### PR TITLE
further tweaks to max message size exception message

### PR DESCRIPTION
**Pull request by adamralph**
relates to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/980 and https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/981

### CODE REVIEW

**Comment by adamralph** [comment]
How do we ensure that #980 appears in the release notes for the next release? Should be added to a milestone?

**Comment by lailabougria** [comment]
Good point @adamralph, yes it should be added to a milestone.

**Comment by lailabougria** [comment]
Looks like this would go into 4.1

**Review by lailabougria — APPROVED** [review]

**Review by andreasohlund — APPROVED** [review]

**Comment by adamralph** [comment]
I created a vNext milestone and put #980 on that. Whoever is releasing can determine the version.

**Pull request merged**
